#pragma once

#define DEBUG

#define BOD 9600

#define UI_BACKEND_U8G2 0
#define UI_BACKEND_GYVER 1

#define UI_BACKEND UI_BACKEND_U8G2
// #define UI_BACKEND UI_BACKEND_GYVER

// #define OLED_CLASS U8G2_SSD1306_128X64_NONAME_1_HW_I2C
#define OLED_CLASS U8G2_SH1106_128X64_NONAME_1_HW_I2C

#if UI_BACKEND == UI_BACKEND_U8G2 && !defined(OLED_CLASS)
#error "не задан OLED_CLASS"+9
#endif

#if UI_BACKEND != UI_BACKEND_U8G2 && UI_BACKEND != UI_BACKEND_GYVER
#error "UI_BACKEND должен быть UI_BACKEND_U8G2 или UI_BACKEND_GYVER"
#endif

#define START_MENU_DURATION 1000 * 2
#define TEMP_DELAY 1000

#define SHOW_START_WINDOW
