#pragma once

// #define DEBUG
#define DEBUG_COMMAND
#define VERSION "V: 0.1"

#define BOD 9600

#define UI_BACKEND_U8G2 0
#define UI_BACKEND_GYVER 1

#define UI_BACKEND UI_BACKEND_U8G2
// #define UI_BACKEND UI_BACKEND_GYVER

#define BTN_BACKEND_ONE_BUTTON 0
#define BTN_BACKEND_CUSTOM 1

#define BTN_BACKEND BTN_BACKEND_ONE_BUTTON
// #define BTN_BACKEND BTN_BACKEND_CUSTOM

// #define OLED_CLASS U8G2_SSD1306_128X64_NONAME_1_HW_I2C
#define OLED_CLASS U8G2_SH1106_128X64_NONAME_1_HW_I2C

#if UI_BACKEND == UI_BACKEND_U8G2 && !defined(OLED_CLASS)
#error "не задан OLED_CLASS"+9
#endif

#if UI_BACKEND != UI_BACKEND_U8G2 && UI_BACKEND != UI_BACKEND_GYVER
#error "UI_BACKEND должен быть UI_BACKEND_U8G2 или UI_BACKEND_GYVER"
#endif

#define START_MENU_DURATION 1000 * 2
#define TEMP_DELAY 1000

#define SHOW_START_WINDOW
#define ENABLE_COMMANDS
#define DEBOUNCE_DURATION 50